name: Share data between 2 jobs

on: [push]

jobs:
  upload-data-job:
    name: Upload data to artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: mkdir -p homework
      - shell: bash
        run: |
          echo Hello World! > homework/hello-world.txt |
          echo Hello World! > homework/hello-world2.txt
      - name: Upload hello world file
        uses: actions/upload-artifact@v1
        with:
          name: hello-world
          path: homework

  download-data-job:
    name: Download data from artifact
    needs: upload-data-job
    runs-on: windows-latest
    steps:
      - name: Download hello world file
        uses: actions/download-artifact@v1
        with:
          name: hello-world
          path: homework
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: homework
